### ISSUE TITLE
Broken links in navbar

### ISSUE THREAD

**Issue by Peleke** [bklynate/bootstrap-bp#1]
Careful with the path, here:

```
<!-- in index.html -->
<ul class="nav navbar-nav navbar-right navbar-right-custom">
  <li><a href="/contact.html">Contact</a></li>
  <li><a href="/portfolio.html">Portfolio</a></li>
  <li><a href="/">About</a></li>
</ul>
```

This doesn't work as desired on `gh-pages`. Otherwise looks great.

**Comment by bklynate** [comment]
I forgot to resubmit with the heroku link. I think i'll be using heroku over gh-pages. I find heroku easier to deploy to.

https://rcb-bp.herokuapp.com/
